import { NextResponse,type NextRequest } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { apiError } from "@/server/http";
import { requireOperator } from "@/server/operator-auth";
import { onboardTenant } from "@/server/services/onboarding";
const schema=z.object({businessName:z.string().min(2),legalName:z.string().optional(),email:z.string().email(),phone:z.string().min(7),town:z.string().min(2),address:z.string().min(3),currency:z.string(),timezone:z.string(),code:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),plan:z.enum(["Starter","Growth","Business"]),status:z.enum(["Trial","Active"]),trialEnd:z.string().optional(),receiptName:z.string().min(2),adminName:z.string().min(2),adminEmail:z.string().email(),adminPhone:z.string().min(7),temporaryPassword:z.string().min(12),adminPin:z.string().regex(/^\d{4,8}$/),branchName:z.string().min(2),branchCode:z.string().min(2)});
const limits={Starter:{monthlyPrice:1500,yearlyPrice:15000,maxBranches:1,maxUsers:5,maxProducts:500},Growth:{monthlyPrice:4500,yearlyPrice:45000,maxBranches:5,maxUsers:25,maxProducts:5000},Business:{monthlyPrice:9000,yearlyPrice:90000,maxBranches:50,maxUsers:100,maxProducts:50000}} as const;
const publicUrl=(path:string)=>new URL(path,process.env.APP_URL??"http://192.241.151.24");
export async function POST(req:NextRequest){try{const ctx=await requireOperator(req);const raw=Object.fromEntries(await req.formData());const input=schema.parse(raw);const config=limits[input.plan];const plan=await db.subscriptionPlan.upsert({where:{name:input.plan},create:{name:input.plan,...config,enabledFeatures:["pos","inventory","customers","reports"]},update:{active:true}});const result=await onboardTenant(db,ctx,{code:input.code.toUpperCase(),slug:input.slug.toLowerCase(),name:input.businessName,legalName:input.legalName||undefined,email:input.email.toLowerCase(),phone:input.phone,currency:input.currency,timezone:input.timezone,receiptName:input.receiptName,planId:plan.id,status:input.status.toUpperCase() as "TRIAL"|"ACTIVE",trialEndsAt:input.trialEnd?new Date(`${input.trialEnd}T23:59:59Z`):undefined,branch:{code:input.branchCode.toUpperCase(),name:input.branchName,address:`${input.address}, ${input.town}`},admin:{fullName:input.adminName,email:input.adminEmail.toLowerCase(),phone:input.adminPhone,temporaryPassword:input.temporaryPassword,pin:input.adminPin}});return NextResponse.redirect(publicUrl(`/operator/tenants/${result.tenant.slug}?created=1`),303)}catch(error){const message=error instanceof z.ZodError?error.issues[0]?.message:"Unable to onboard client. Check that the tenant code, slug and administrator email are unique.";return NextResponse.redirect(publicUrl(`/operator/tenants/new?error=${encodeURIComponent(message)}`),303)}}
